conditions:
    - system:x86_64-linux
    - system:x86_64-darwin
    - system:aarch64-linux
    - system:i686-linux
name: cowsay
version: 3.8.4
description: "Program which generates ASCII pictures of a cow with a message"
homepage: "https://cowsay.diamonds"
changelog: "https://github.com/cowsay-org/cowsay/releases/tag/v${finalAttrs.version}"
license: lib.licenses.gpl3Only
platforms: lib.platforms.all
mainProgram: "cowsay"
maintainers: 
    - rob
    - anthonyroussel
output:
    lib: null
    executables:
        - cowsay
    files:
flake: ./flake.nix
input:
    paths: []
    attrSources:
        "github:NixOS/nixpkgs/nixos-25.05":
            - ? [ ] : nixpkgs.fetchFromGitHub
            - ? [ ] : nixpkgs.lib.platforms.all
            - ? [ ] : nixpkgs.lib.licenses.gpl3Only
            - ? [ ] : nixpkgs.lib.licenses.maintainers.rob
            - ? [ ] : nixpkgs.lib.licenses.maintainers.anthonyroussel
            - ? [ system:x86_64-linux ] : nixpkgs.legacyPackages.x86_64-linux.makeWrapper
            - ? [ system:x86_64-linux ] : nixpkgs.legacyPackages.x86_64-linux.nix-update-script
            - ? [ system:x86_64-linux ] : nixpkgs.legacyPackages.x86_64-linux.perl
            - ? [ system:x86_64-linux ] : nixpkgs.legacyPackages.x86_64-linux.stdenv.mkDerivation
            - ? [ system:x86_64-linux ] : nixpkgs.legacyPackages.x86_64-linux.testers.testVersion
            - ? [ system:x86_64-darwin ] : nixpkgs.legacyPackages.x86_64-darwin.makeWrapper
            - ? [ system:x86_64-darwin ] : nixpkgs.legacyPackages.x86_64-darwin.nix-update-script
            - ? [ system:x86_64-darwin ] : nixpkgs.legacyPackages.x86_64-darwin.perl
            - ? [ system:x86_64-darwin ] : nixpkgs.legacyPackages.x86_64-darwin.stdenv.mkDerivation
            - ? [ system:x86_64-darwin ] : nixpkgs.legacyPackages.x86_64-darwin.testers.testVersion
            - ? [ system:aarch64-linux ] : nixpkgs.legacyPackages.aarch64-linux.makeWrapper
            - ? [ system:aarch64-linux ] : nixpkgs.legacyPackages.aarch64-linux.nix-update-script
            - ? [ system:aarch64-linux ] : nixpkgs.legacyPackages.aarch64-linux.perl
            - ? [ system:aarch64-linux ] : nixpkgs.legacyPackages.aarch64-linux.stdenv.mkDerivation
            - ? [ system:aarch64-linux ] : nixpkgs.legacyPackages.aarch64-linux.testers.testVersion
            - ? [ system:i686-linux ] : nixpkgs.legacyPackages.i686-linux.makeWrapper
            - ? [ system:i686-linux ] : nixpkgs.legacyPackages.i686-linux.nix-update-script
            - ? [ system:i686-linux ] : nixpkgs.legacyPackages.i686-linux.perl
            - ? [ system:i686-linux ] : nixpkgs.legacyPackages.i686-linux.stdenv.mkDerivation
            - ? [ system:i686-linux ] : nixpkgs.legacyPackages.i686-linux.testers.testVersion