{
    description = "A homemade cowsay, built by denix (no nixpkgs, no external source)";

    inputs = { };

    outputs = { self }:
        let
            system = builtins.currentSystem;
        in
        {
            packages.${system}.default = derivation {
                name = "cowsay-homemade-1.0";
                inherit system;
                builder = "/bin/sh";
                # This is an intentionally impure demo: it uses host coreutils
                # (cat, wc, chmod). denix no longer leaks the host PATH into
                # builders by default, so we declare it explicitly here. The
                # stdenv-lite example shows the pure, dependency-provided way.
                PATH = "/usr/bin:/bin";
                # The whole package is generated by the builder: it writes a
                # self-contained POSIX-sh cowsay script into $out/bin/cowsay.
                # No ${ } shell expansions are used so Nix never tries to
                # interpolate them (Nix only treats `${` specially).
                args = [
                    "-c"
                    ''
                        set -e
                        mkdir -p "$out/bin"
                        cat > "$out/bin/cowsay" <<'COWSAY_SCRIPT'
                        #!/bin/sh
                        # homemade cowsay
                        text="$*"
                        [ -z "$text" ] && text="moo"
                        width=$(printf '%s' "$text" | wc -c)
                        width=$((width + 2))
                        line=""
                        i=0
                        while [ "$i" -lt "$width" ]; do
                            line="$line"_
                            i=$((i + 1))
                        done
                        bot=""
                        i=0
                        while [ "$i" -lt "$width" ]; do
                            bot="$bot"-
                            i=$((i + 1))
                        done
                        printf ' %s \n' "$line"
                        printf '< %s >\n' "$text"
                        printf ' %s \n' "$bot"
                        cat <<'COW'
                                \   ^__^
                                 \  (oo)\_______
                                    (__)\       )\/\
                                        ||----w |
                                        ||     ||
                        COW
                        COWSAY_SCRIPT
                        chmod +x "$out/bin/cowsay"
                    ''
                ];
            };
        };
}
